import { StyleSheet } from 'react-native';

import { useAppTheme } from '@/providers/theme-provider';

export function useUserSearchStyles() {
  const { theme } = useAppTheme();
  const isDark = theme === 'dark';

  return StyleSheet.create({
    safeArea: { flex: 1 },
    keyboardView: { flex: 1 },
    screen: {
      ...StyleSheet.absoluteFill,
      zIndex: 10,
      justifyContent: 'flex-end',
    },
    backdrop: {
      ...StyleSheet.absoluteFill,
      backgroundColor: 'rgba(7, 5, 12, 0.54)',
    },
    backdropPressable: {
      ...StyleSheet.absoluteFill,
    },
    sheetSurface: {
      overflow: 'hidden',
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      backgroundColor: isDark ? '#171220' : '#FAF8FD',
      boxShadow: '0 -12px 36px rgba(7,5,12,0.22)',
    },
    grabberArea: {
      height: 25,
      alignItems: 'center',
      justifyContent: 'center',
    },
    grabber: {
      width: 42,
      height: 5,
      borderRadius: 3,
      backgroundColor: isDark ? 'rgba(218,211,229,0.38)' : 'rgba(67,58,78,0.28)',
    },
    header: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: 0,
    },
    headingCopy: { flex: 1, paddingRight: 12 },
    title: { fontSize: 24, lineHeight: 31 },
    subtitle: { paddingTop: 3, fontSize: 12, lineHeight: 18 },
    closeButton: {
      width: 48,
      height: 48,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? '#2B2438' : '#EEEAF4',
    },
    pressed: { opacity: 0.68 },
    searchGroup: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 8, gap: 8 },
    label: {
      color: isDark ? '#D7D0E3' : '#4C4557',
      paddingLeft: 3,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '600',
    },
    searchField: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 11,
      borderRadius: 19,
      borderCurve: 'continuous',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(192,177,255,0.18)' : 'rgba(93,72,180,0.13)',
      paddingHorizontal: 16,
      backgroundColor: isDark ? '#262030' : '#FFFFFF',
      boxShadow: isDark ? '0 10px 24px rgba(0,0,0,0.18)' : '0 10px 24px rgba(65,48,125,0.08)',
    },
    searchIcon: { color: isDark ? '#BBAEFF' : '#6654C7' },
    input: {
      minWidth: 0,
      flex: 1,
      paddingVertical: 0,
      color: isDark ? '#FFFFFF' : '#201B29',
      fontFamily: 'PlusJakartaSans',
      fontSize: 16,
      lineHeight: 22,
    },
    clearButton: {
      width: 48,
      height: 48,
      marginRight: -12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    clearIcon: { color: isDark ? '#A8A0B3' : '#7C7487' },
    listContent: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 8, paddingBottom: 32 },
    state: {
      flex: 1,
      minHeight: 240,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 30,
      paddingBottom: 44,
    },
    stateIcon: {
      width: 64,
      height: 64,
      borderRadius: 23,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 17,
      backgroundColor: isDark ? 'rgba(124,101,225,0.17)' : '#EEE9FF',
    },
    stateIconColor: { color: isDark ? '#BEAFFF' : '#6654C7' },
    stateTitle: { fontSize: 17, lineHeight: 23, textAlign: 'center' },
    stateMessage: { paddingTop: 6, fontSize: 13, lineHeight: 20, textAlign: 'center' },
    retryButton: {
      minHeight: 48,
      justifyContent: 'center',
      marginTop: 18,
      borderRadius: 16,
      paddingHorizontal: 20,
      backgroundColor: '#6654C7',
    },
    retryText: { color: '#FFFFFF', fontSize: 13, lineHeight: 18, fontWeight: '700' },
    resultRow: {
      minHeight: 82,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 13,
      borderRadius: 21,
      borderCurve: 'continuous',
      paddingHorizontal: 13,
      paddingVertical: 11,
    },
    resultRowPressed: { backgroundColor: isDark ? '#292233' : '#F0ECF6' },
    avatarWrap: { width: 58, height: 58 },
    avatar: { width: 58, height: 58, borderRadius: 21, borderCurve: 'continuous' },
    avatarPlaceholder: {
      width: 58,
      height: 58,
      borderRadius: 21,
      borderCurve: 'continuous',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? '#55488A' : '#E7E0FF',
    },
    initials: { color: isDark ? '#F2EEFF' : '#5948A9', fontSize: 18, fontWeight: '700' },
    flagBadge: {
      position: 'absolute',
      right: -5,
      bottom: -4,
      width: 25,
      height: 25,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: isDark ? '#171220' : '#FAF8FD',
      backgroundColor: isDark ? '#302A3E' : '#FFFFFF',
    },
    resultCopy: { flex: 1, minWidth: 0, gap: 4 },
    resultName: { fontSize: 16, lineHeight: 22 },
    languageLine: { flexDirection: 'row', alignItems: 'center', gap: 5 },
    languageText: { fontSize: 11, lineHeight: 16 },
    arrow: { color: isDark ? '#817989' : '#9A92A2', fontSize: 11, lineHeight: 16 },
    chevron: { color: isDark ? '#817989' : '#9A92A2' },
    separator: {
      height: StyleSheet.hairlineWidth,
      marginLeft: 84,
      backgroundColor: isDark ? 'rgba(255,255,255,0.09)' : 'rgba(64,52,88,0.12)',
    },
  });
}
