const LANGUAGE_COUNTRY_CODES: Record<string, string> = {
  Arabic: 'SA',
  Armenian: 'AM',
  Azerbaijani: 'AZ',
  Bengali: 'BD',
  'Chinese (Mandarin)': 'CN',
  Czech: 'CZ',
  Danish: 'DK',
  Dutch: 'NL',
  English: 'GB',
  Filipino: 'PH',
  Finnish: 'FI',
  French: 'FR',
  Georgian: 'GE',
  German: 'DE',
  Greek: 'GR',
  Hebrew: 'IL',
  Hindi: 'IN',
  Hungarian: 'HU',
  Indonesian: 'ID',
  Italian: 'IT',
  Japanese: 'JP',
  Kazakh: 'KZ',
  Korean: 'KR',
  Malay: 'MY',
  Norwegian: 'NO',
  Persian: 'IR',
  Polish: 'PL',
  Portuguese: 'PT',
  Romanian: 'RO',
  Russian: 'RU',
  Spanish: 'ES',
  Swahili: 'KE',
  Swedish: 'SE',
  Tajik: 'TJ',
  Thai: 'TH',
  Turkish: 'TR',
  Ukrainian: 'UA',
  Urdu: 'PK',
  Uzbek: 'UZ',
  Vietnamese: 'VN',
};

export const getLanguageCountryCode = (language?: string | null) =>
  language ? LANGUAGE_COUNTRY_CODES[language] : undefined;
