import { StyleSheet } from 'react-native';

import { useAppTheme } from '@/providers/theme-provider';

export const useEditProfileStyles = () => {
  const { theme } = useAppTheme();
  const isDark = theme === 'dark';

  return StyleSheet.create({
    keyboardView: { flex: 1, width: '100%' },
    scrollContent: { flexGrow: 1 },
    safeArea: {
      width: '100%',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 36,
    },
    content: { width: '100%', maxWidth: 520, gap: 20 },
    header: { minHeight: 52, flexDirection: 'row', alignItems: 'center' },
    backButton: {
      width: 42,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 21,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.10)' : 'rgba(91,70,176,0.10)',
      backgroundColor: isDark ? 'rgba(255,255,255,0.07)' : 'rgba(255,255,255,0.78)',
    },
    icon: { color: isDark ? '#F0EAF9' : '#302A3A' },
    headerCopy: { flex: 1, alignItems: 'center', gap: 1 },
    headerTitle: { fontSize: 17, lineHeight: 23 },
    headerSubtitle: { fontSize: 11, lineHeight: 16 },
    headerSpacer: { width: 42 },
    pressed: { opacity: 0.65 },
    formCard: {
      padding: 20,
      gap: 19,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(151,134,219,0.22)' : 'rgba(91,70,176,0.10)',
      backgroundColor: isDark ? 'rgba(31,25,47,0.94)' : 'rgba(255,255,255,0.94)',
      shadowColor: isDark ? '#000000' : '#3B309E',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: isDark ? 0.2 : 0.07,
      shadowRadius: 24,
      elevation: 3,
    },
    field: { gap: 8 },
    labelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    label: {
      color: isDark ? '#D8D0E8' : '#34303D',
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '600',
    },
    characterCount: { fontSize: 10, lineHeight: 15 },
    textArea: {
      minHeight: 132,
      paddingHorizontal: 15,
      paddingVertical: 13,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: isDark ? '#4A405F' : '#DED8EC',
      backgroundColor: isDark ? '#171321' : '#FBFAFE',
      color: isDark ? '#F5F1FF' : '#221E2B',
      fontFamily: 'PlusJakartaSans',
      fontSize: 15,
      lineHeight: 22,
    },
    placeholder: { color: isDark ? '#8E849D' : '#91899E' },
    inputError: { borderColor: '#D64545' },
    error: {
      color: isDark ? '#FF9A9A' : '#B42318',
      fontSize: 12,
      lineHeight: 17,
    },
    levelRow: { flexDirection: 'row', gap: 8 },
    levelPill: {
      flex: 1,
      minHeight: 44,
      paddingHorizontal: 6,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: isDark ? '#4A405F' : '#DED8EC',
      backgroundColor: isDark ? '#171321' : '#FBFAFE',
    },
    levelPillSelected: {
      borderColor: '#6654C7',
      backgroundColor: isDark ? 'rgba(102,84,199,0.28)' : '#EEEAFB',
    },
    levelText: { fontSize: 11, lineHeight: 16, fontWeight: '600' },
    levelTextSelected: { color: isDark ? '#C9BEFF' : '#5643B4' },
    interestGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
    interestPill: {
      minHeight: 41,
      paddingHorizontal: 13,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: isDark ? '#4A405F' : '#DED8EC',
      backgroundColor: isDark ? '#171321' : '#FBFAFE',
    },
    interestPillSelected: {
      borderColor: '#6654C7',
      backgroundColor: isDark ? 'rgba(102,84,199,0.28)' : '#EEEAFB',
    },
    interestText: {
      color: isDark ? '#D8D0E8' : '#4B4555',
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '600',
    },
    interestTextSelected: { color: isDark ? '#C9BEFF' : '#5643B4' },
    serverError: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,140,140,0.22)' : '#FFD0CC',
      backgroundColor: isDark ? 'rgba(255,112,112,0.10)' : '#FFF1F0',
    },
    serverErrorText: {
      color: isDark ? '#FFAAAA' : '#9F2018',
      fontSize: 12,
      lineHeight: 18,
    },
  });
};
