import { StyleSheet } from 'react-native';

import { useAppTheme } from '@/providers/theme-provider';

export const useProfileStyles = () => {
  const { theme } = useAppTheme();
  const isDark = theme === 'dark';

  return StyleSheet.create({
    scrollContent: { flexGrow: 1, paddingBottom: 118 },
    safeArea: {
      width: '100%',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingTop: 16,
    },
    content: { width: '100%', maxWidth: 520, gap: 16 },
    titleRow: { paddingHorizontal: 2, paddingBottom: 4 },
    screenTitle: { fontSize: 30, lineHeight: 38, letterSpacing: -0.6 },
    screenSubtitle: { marginTop: 3, fontSize: 13, lineHeight: 19 },
    profileCard: {
      alignItems: 'center',
      padding: 22,
      gap: 18,
      borderRadius: 26,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(151,134,219,0.22)' : 'rgba(91,70,176,0.10)',
      backgroundColor: isDark ? 'rgba(31,25,47,0.94)' : 'rgba(255,255,255,0.94)',
      shadowColor: isDark ? '#000000' : '#3B309E',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: isDark ? 0.2 : 0.07,
      shadowRadius: 24,
      elevation: 3,
    },
    avatarArea: { alignItems: 'center', gap: 8 },
    avatarButton: { width: 124, height: 124, borderRadius: 62 },
    avatar: { width: '100%', height: '100%', borderRadius: 62 },
    initialsAvatar: {
      width: '100%',
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 62,
      backgroundColor: isDark ? '#342A51' : '#E9E3FA',
      borderWidth: 2,
      borderColor: isDark ? '#554878' : '#D4C9F2',
    },
    initials: {
      color: isDark ? '#D6CCFF' : '#5B49B8',
      fontSize: 36,
      lineHeight: 44,
      fontWeight: '700',
    },
    editBadge: {
      position: 'absolute',
      right: 1,
      bottom: 2,
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 18,
      borderWidth: 3,
      borderColor: isDark ? '#1F192F' : '#FFFFFF',
      backgroundColor: '#6654C7',
    },
    removePhoto: {
      color: isDark ? '#C5B8FF' : '#5B49B8',
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '600',
    },
    error: {
      maxWidth: 280,
      color: isDark ? '#FFAAAA' : '#B42318',
      fontSize: 12,
      lineHeight: 18,
      textAlign: 'center',
    },
    identity: { alignItems: 'center', gap: 5 },
    displayName: { fontSize: 27, lineHeight: 34, letterSpacing: -0.5, textAlign: 'center' },
    countryRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    countryText: { fontSize: 13, lineHeight: 18 },
    pressed: { opacity: 0.65 },
    sectionCard: {
      padding: 20,
      gap: 16,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(151,134,219,0.18)' : 'rgba(91,70,176,0.09)',
      backgroundColor: isDark ? 'rgba(27,22,39,0.92)' : 'rgba(255,255,255,0.91)',
    },
    sectionTitle: { fontSize: 15, lineHeight: 21 },
    languageRow: { minHeight: 50, flexDirection: 'row', alignItems: 'center', gap: 12 },
    flagCircle: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 22,
      overflow: 'hidden',
      backgroundColor: isDark ? '#292238' : '#F2EEF9',
    },
    languageFlagFallback: { color: isDark ? '#C9BEFF' : '#6654C7' },
    languageCopy: { flex: 1, gap: 1 },
    eyebrow: {
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    languageName: { fontSize: 15, lineHeight: 21 },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: isDark ? '#40384E' : '#E7E1EE',
    },
    levelPill: {
      paddingHorizontal: 11,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: isDark ? 'rgba(102,84,199,0.28)' : '#EEEAFB',
    },
    levelText: {
      color: isDark ? '#C9BEFF' : '#5643B4',
      fontSize: 11,
      lineHeight: 15,
      fontWeight: '700',
    },
    interests: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
    interestPill: {
      paddingHorizontal: 13,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: isDark ? '#2A2338' : '#F1EDF8',
    },
    interestText: { fontSize: 12, lineHeight: 17, fontWeight: '600' },
    bio: { fontSize: 14, lineHeight: 23 },
    appearanceSubtitle: { marginTop: 4, fontSize: 12, lineHeight: 18 },
    themeOptions: { flexDirection: 'row', gap: 9 },
    themeOption: {
      minHeight: 64,
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? '#40384E' : '#E5DFEC',
      backgroundColor: isDark ? '#251F33' : '#F5F2F9',
    },
    themeOptionSelected: { borderColor: '#6654C7', backgroundColor: '#6654C7' },
    themeOptionText: {
      color: isDark ? '#C7BECE' : '#625A6B',
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '700',
    },
    themeOptionTextSelected: { color: '#FFFFFF' },
    logoutButton: {
      minHeight: 54,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 9,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,138,138,0.28)' : 'rgba(180,35,24,0.18)',
      backgroundColor: isDark ? 'rgba(122,37,46,0.16)' : 'rgba(255,243,242,0.9)',
    },
    logoutText: {
      color: isDark ? '#FFAAAA' : '#B42318',
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '700',
    },
  });
};
