import { useAppTheme } from '@/providers/theme-provider';
import { Platform, StyleSheet } from 'react-native';

import { CHAT_HEADER_HEIGHT } from '../constants';

export const useChatStyles = () => {
  const { theme } = useAppTheme();
  const isDark = theme === 'dark';
  const border = isDark ? 'rgba(190,176,255,0.13)' : 'rgba(97,76,190,0.10)';

  return StyleSheet.create({
    safeArea: { flex: 1, width: '100%', maxWidth: 720, alignSelf: 'center' },
    header: {
      height: CHAT_HEADER_HEIGHT,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: border,
      backgroundColor: isDark ? 'rgba(25,21,35,0.94)' : 'rgba(250,249,253,0.96)',
    },
    backButton: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 7,
    },
    pressed: { opacity: 0.65 },
    headerIcon: { color: isDark ? '#F5F1FF' : '#312C3C' },
    headerProfileButton: {
      flex: 1,
      minWidth: 0,
      height: '100%',
      flexDirection: 'row',
      alignItems: 'center',
    },
    headerAvatarWrap: { width: 42, height: 42 },
    avatar: { width: 42, height: 42, borderRadius: 21 },
    avatarPlaceholder: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? '#55488A' : '#E8E2FF',
    },
    headerCountryBadge: {
      position: 'absolute',
      right: -3,
      bottom: -2,
      width: 20,
      height: 20,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 10,
      borderWidth: 2,
      borderColor: isDark ? '#191523' : '#FAF9FD',
      backgroundColor: isDark ? '#302A3E' : '#FFFFFF',
    },
    initials: { color: isDark ? '#F2EEFF' : '#5846AA', fontSize: 12, lineHeight: 17 },
    headerCopy: { flex: 1, minWidth: 0, marginLeft: 11 },
    headerName: { fontSize: 15, lineHeight: 20 },
    onlineText: { color: isDark ? '#9F96AD' : '#7A7285', fontSize: 10, lineHeight: 15 },
    chat: { flex: 1, backgroundColor: isDark ? '#181420' : '#F8F6FC' },
    messagesContainer: { backgroundColor: isDark ? '#181420' : '#F8F6FC' },
    messageList: { paddingHorizontal: 12, paddingTop: 12, paddingBottom: 10 },
    messageLane: { width: '100%' },
    messageRowGrouped: { marginBottom: 3 },
    messageRowSeparated: { marginBottom: 10 },
    messageSwipeable: { maxWidth: '78%', overflow: 'visible' },
    messageSwipeableLeft: { alignSelf: 'flex-start', marginLeft: 2 },
    messageSwipeableRight: { alignSelf: 'flex-end', marginRight: 2 },
    bubble: {
      minWidth: 74,
      maxWidth: '100%',
      borderRadius: 20,
      paddingTop: 10,
      paddingHorizontal: 13,
      paddingBottom: 7,
    },
    bubbleLeft: {
      backgroundColor: isDark ? '#302A3D' : '#FFFFFF',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: border,
      shadowColor: '#000000',
      shadowOpacity: isDark ? 0.12 : 0.06,
      shadowRadius: 7,
      shadowOffset: { width: 0, height: 3 },
    },
    bubbleRight: {
      backgroundColor: isDark ? '#735FDC' : '#6654C7',
      shadowColor: '#503CB9',
      shadowOpacity: 0.2,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
    },
    bubbleJoinAboveLeft: { borderTopLeftRadius: 7 },
    bubbleJoinBelowLeft: { borderBottomLeftRadius: 7 },
    bubbleJoinAboveRight: { borderTopRightRadius: 7 },
    bubbleJoinBelowRight: { borderBottomRightRadius: 7 },
    messageReply: {
      minWidth: 126,
      marginBottom: 7,
      borderLeftWidth: 3,
      borderRadius: 10,
      paddingHorizontal: 9,
      paddingVertical: 7,
    },
    messageReplyLeft: {
      backgroundColor: isDark ? 'rgba(123,102,218,0.13)' : '#F0ECFA',
      borderLeftColor: '#735FDC',
    },
    messageReplyRight: {
      backgroundColor: 'rgba(255,255,255,0.13)',
      borderLeftColor: 'rgba(255,255,255,0.75)',
    },
    messageReplyAuthor: { fontSize: 10, lineHeight: 14, marginBottom: 1 },
    messageReplyAuthorLeft: { color: isDark ? '#BEB0FF' : '#654FC1' },
    messageReplyAuthorRight: { color: '#FFFFFF' },
    messageReplyText: { fontSize: 11, lineHeight: 16 },
    messageReplyTextLeft: { color: isDark ? '#B8B0C4' : '#6E6679' },
    messageReplyTextRight: { color: 'rgba(255,255,255,0.76)' },
    bubbleTextLeft: { color: isDark ? '#F7F3FC' : '#292432', fontSize: 15, lineHeight: 21 },
    bubbleTextRight: { color: '#FFFFFF', fontSize: 15, lineHeight: 21 },
    bubbleMeta: {
      minHeight: 14,
      marginTop: 3,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 4,
    },
    messageTimeLeft: { color: isDark ? '#9F97AA' : '#8A8491', fontSize: 9, lineHeight: 12 },
    messageTimeRight: { color: 'rgba(255,255,255,0.68)', fontSize: 9, lineHeight: 12 },
    pendingDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.65)' },
    inputToolbar: {
      minHeight: 62,
      paddingHorizontal: 10,
      paddingTop: 8,
      backgroundColor: isDark ? '#211C2A' : '#FFFFFF',
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: border,
    },
    inputPrimary: {
      minHeight: 46,
      alignItems: 'flex-end',
      borderRadius: 23,
      backgroundColor: isDark ? '#302A3C' : '#F2EFF6',
      paddingLeft: 8,
      paddingRight: 4,
    },
    composer: {
      flex: 1,
      minHeight: 42,
      maxHeight: 110,
      paddingTop: 11,
      paddingBottom: 9,
      paddingHorizontal: 7,
      color: isDark ? '#F5F1FA' : '#292432',
      fontSize: 14,
      lineHeight: 20,
    },
    placeholder: { color: isDark ? '#8E879A' : '#918A99' },
    sendContainer: { width: 44, height: 46, alignItems: 'center', justifyContent: 'center' },
    sendButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#6654C7',
    },
    sendButtonDisabled: { opacity: 0.42 },
    replySwipeAction: { width: 50, alignItems: 'center', justifyContent: 'center' },
    replySwipeIcon: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#6654C7',
      shadowColor: '#3D2A9E',
      shadowOpacity: 0.2,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
    },
    replyPreview: {
      minHeight: 54,
      marginHorizontal: 2,
      marginBottom: 8,
      flexDirection: 'row',
      alignItems: 'center',
      overflow: 'hidden',
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? 'rgba(190,176,255,0.15)' : 'rgba(97,76,190,0.12)',
      backgroundColor: isDark ? '#2A2436' : '#F5F2FC',
    },
    replyPreviewAccent: { width: 4, alignSelf: 'stretch', backgroundColor: '#735FDC' },
    replyPreviewCopy: { flex: 1, minWidth: 0, paddingHorizontal: 11, paddingVertical: 8 },
    replyPreviewTitle: { color: isDark ? '#C5BAFF' : '#604DB7', fontSize: 10, lineHeight: 14 },
    replyPreviewText: {
      color: isDark ? '#B4ADBF' : '#716A7B',
      fontSize: 11,
      lineHeight: 16,
      marginTop: 1,
    },
    replyPreviewClose: {
      width: 38,
      height: 38,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 4,
    },
    replyPreviewCloseColor: { color: isDark ? '#B7AFBF' : '#756D7F' },
    olderMessagesLoader: {
      minHeight: 40,
      marginVertical: 8,
      marginHorizontal: 20,
      paddingHorizontal: 13,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      alignSelf: 'center',
      borderRadius: 20,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? 'rgba(190,176,255,0.15)' : 'rgba(97,76,190,0.12)',
      backgroundColor: isDark ? '#272130' : '#F2EEFA',
    },
    olderMessagesAccent: { color: isDark ? '#B7A8FF' : '#6654C7' },
    olderMessagesText: { color: isDark ? '#B8B0C4' : '#6D6578', fontSize: 10, lineHeight: 15 },
    typingText: {
      color: isDark ? '#B9AECE' : '#756D82',
      fontSize: 11,
      lineHeight: 16,
      marginLeft: 17,
      marginBottom: 5,
    },
    emptyChat: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 34,
      ...Platform.select({ ios: { transform: [{ scaleY: -1 }] } }),
    },
    emptyTitle: { fontSize: 17, lineHeight: 23, textAlign: 'center' },
    emptyMessage: { marginTop: 6, fontSize: 12, lineHeight: 19, textAlign: 'center' },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 9,
      backgroundColor: isDark ? '#4A2630' : '#FFF0F1',
    },
    errorBannerText: {
      flex: 1,
      color: isDark ? '#FFBAC1' : '#A93240',
      fontSize: 11,
      lineHeight: 16,
    },
    centered: {
      flex: 1,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 28,
    },
    loadingText: { fontSize: 13, marginTop: 14 },
    errorTitle: { fontSize: 18, textAlign: 'center', marginBottom: 8 },
    errorMessage: { fontSize: 13, lineHeight: 20, textAlign: 'center' },
    errorButton: {
      marginTop: 20,
      borderRadius: 999,
      paddingHorizontal: 18,
      paddingVertical: 10,
      backgroundColor: '#6654C7',
    },
    errorButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  });
};

export type ChatStyles = ReturnType<typeof useChatStyles>;
