import { StyleSheet } from 'react-native';

import { useAppTheme } from '@/providers/theme-provider';

export const useChatsStyles = () => {
  const { theme } = useAppTheme();
  const isDark = theme === 'dark';
  const card = isDark ? 'rgba(38,32,52,0.94)' : 'rgba(255,255,255,0.92)';
  const border = isDark ? 'rgba(190,176,255,0.12)' : 'rgba(97,76,190,0.09)';
  const skeleton = isDark ? '#332D42' : '#EAE6F0';

  return StyleSheet.create({
    safeArea: { flex: 1, width: '100%' },
    content: {
      flexGrow: 1,
      width: '100%',
      maxWidth: 560,
      alignSelf: 'center',
      paddingHorizontal: 20,
      paddingBottom: 120,
    },
    header: {
      paddingTop: 16,
      paddingBottom: 24,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    title: { fontSize: 32, lineHeight: 39 },
    subtitle: { fontSize: 13, lineHeight: 20, marginTop: 3 },
    headerBadge: {
      width: 46,
      height: 46,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#6B57CA',
    },
    row: {
      minHeight: 82,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 13,
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingVertical: 13,
      backgroundColor: card,
      borderWidth: 1,
      borderColor: border,
    },
    pressed: { opacity: 0.72, transform: [{ scale: 0.995 }] },
    avatarWrap: { width: 54, height: 54 },
    avatarPressed: { opacity: 0.72, transform: [{ scale: 0.96 }] },
    avatar: { width: 54, height: 54, borderRadius: 27 },
    avatarPlaceholder: {
      width: 54,
      height: 54,
      borderRadius: 27,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? '#55488A' : '#E8E2FF',
    },
    onlineDot: {
      position: 'absolute',
      right: -2,
      bottom: 1,
      width: 14,
      height: 14,
      zIndex: 2,
      elevation: 2,
      borderRadius: 7,
      borderWidth: 2,
      borderColor: isDark ? '#262034' : '#FFFFFF',
      backgroundColor: '#35B879',
    },
    countryBadge: {
      position: 'absolute',
      left: -3,
      bottom: -2,
      width: 24,
      height: 24,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 12,
      borderWidth: 2,
      borderColor: isDark ? '#262034' : '#FFFFFF',
      backgroundColor: isDark ? '#302A3E' : '#FFFFFF',
    },
    initials: { color: isDark ? '#F2EEFF' : '#5846AA', fontSize: 16, lineHeight: 21 },
    rowCopy: { flex: 1, minWidth: 0, gap: 6 },
    rowTop: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    rowBottom: { flexDirection: 'row', alignItems: 'center', gap: 9 },
    name: { flex: 1, fontSize: 15, lineHeight: 20 },
    timestamp: { fontSize: 10, lineHeight: 14 },
    preview: { flex: 1, fontSize: 12, lineHeight: 17 },
    unreadBadge: {
      minWidth: 20,
      height: 20,
      borderRadius: 10,
      paddingHorizontal: 5,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#6B57CA',
    },
    unreadText: { color: '#FFFFFF', fontSize: 9, lineHeight: 12, fontWeight: '700' },
    separator: { height: 10 },
    stateCard: {
      marginTop: 50,
      alignItems: 'center',
      borderRadius: 24,
      paddingHorizontal: 26,
      paddingVertical: 38,
      backgroundColor: card,
      borderWidth: 1,
      borderColor: border,
    },
    stateIcon: {
      width: 58,
      height: 58,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
      backgroundColor: isDark ? 'rgba(130,108,235,0.15)' : '#F0EBFF',
    },
    stateIconColor: { color: isDark ? '#B9ABFF' : '#6654C7' },
    stateTitle: { fontSize: 17, lineHeight: 23, marginBottom: 7 },
    stateMessage: { textAlign: 'center', fontSize: 13, lineHeight: 20 },
    retryButton: {
      marginTop: 18,
      borderRadius: 999,
      paddingHorizontal: 18,
      paddingVertical: 10,
      backgroundColor: '#6654C7',
    },
    retryText: { color: '#FFFFFF', fontSize: 12, lineHeight: 17, fontWeight: '700' },
    skeletonList: { gap: 10 },
    skeletonRow: {
      minHeight: 82,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 13,
      borderRadius: 20,
      padding: 14,
      backgroundColor: card,
      borderWidth: 1,
      borderColor: border,
    },
    skeletonAvatar: { width: 54, height: 54, borderRadius: 27, backgroundColor: skeleton },
    skeletonCopy: { flex: 1, gap: 10 },
    skeletonName: { width: '43%', height: 13, borderRadius: 7, backgroundColor: skeleton },
    skeletonPreview: { width: '78%', height: 10, borderRadius: 6, backgroundColor: skeleton },
  });
};
